# Generated by Django 5.0.6 on 2024-07-13 13:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Editorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial_heading', models.CharField(max_length=300)),
                ('editorial_category', models.CharField(max_length=50)),
                ('editorial_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('editorial_image', models.ImageField(upload_to='images/')),
                ('editorial_des', models.TextField()),
            ],
        ),
    ]
