# Generated by Django 5.0.6 on 2024-07-14 07:09

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editorial', '0002_editorial_editorial_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='editorial',
            name='editorial_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='editorial_heading', unique=True),
        ),
    ]
