# Generated by Django 5.0.6 on 2024-07-12 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sports_heading', models.CharField(max_length=300)),
                ('sports_category', models.CharField(max_length=50)),
                ('sports_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('sports_image', models.ImageField(upload_to='images/')),
                ('sports_des', models.TextField()),
            ],
        ),
    ]
