# Generated by Django 5.0.6 on 2024-07-07 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='topNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topNews_heading', models.CharField(max_length=300)),
                ('topNews_category', models.CharField(max_length=50)),
                ('topNews_date', models.DateTimeField(auto_now=True)),
                ('topNews_image', models.ImageField(upload_to='images/')),
                ('topNews_des', models.TextField()),
            ],
        ),
    ]
