# Generated by Django 5.0.6 on 2024-07-12 05:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('top_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topnews',
            name='topNews_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
